### ISSUE TITLE
Create a grid layout for Stow 1598 / 1633 Law

### ISSUE THREAD

**Issue by mrothwell23** [MoEMLondon/MoEMLissues#15]
Brackets in this chapter are too complicated for Flex.

**Comment by martindholmes** [comment]
Starting with the 1598, this is how we might divide up the first section into a grid:

![grid_for_layout](https://user-images.githubusercontent.com/2412617/214964484-b0f7875c-ec82-4a54-ac1b-aafdba4dad9d.png)

We create the grid based on the number of rows and columns. Then we identify each distinct textual component that will be rendered in the grid, and we figure out the specific set of cells it will live in. Then we create a set of grid-template-areas consisting of those cells, and we assign each textual component to the appropriate grid-template-area. Not trivial, but a good project for getting started with grid.

**Comment by martindholmes** [comment]
@JanelleJenstad @mrothwell23 I have a question on this: When we transcribe/encode this structure, we will be breaking it up into each of its component parts and assigning each part to a specific set of grid cells. In one sense this means that the order in which they're transcribed doesn't matter, but actually we should attempt to transcribe it in a logical sequence that, shorn of its layout information, would still generate something logically coherent. It seems to me that the bracing structure somewhat conceals the actual nested-list structure, which should look something like this:

~~~~~
<list>
  <item>Within the liberties
    <list>
   <item>
     For Judges and Sergeants only
     <list>
       <item>Sergeants Inn in Fleet Street</item>
       <item>Sergeants Inn in Chancery Lane</item>
    </list>
  </item>
[...]
  <item>Without the liberties
[...]
  </item>
</list>
~~~~~

Do you see what I mean? The right-side components are actually subitems of the first-level items, and the items to the left of them are their subitems.

**Comment by martindholmes** [comment]
Per MoEML team meeting 2023-03-08: MH to proceed.

**Comment by martindholmes** [comment]
This is a grid for the 1633, which I'm going to do first; I've revised the encoding already.
![stow_1633_law_toc](https://user-images.githubusercontent.com/2412617/224577988-8f085bba-bada-4c14-bc4a-15506c63e95d.png)

**Comment by martindholmes** [comment]
It turns out that it's not practical to encode the highly-nested conceptual structure of listings like this and then map it onto a CSS grid layout, so I'm going back to absolute positioning for this particular case.

**Comment by martindholmes** [comment]
I've encoded this using conventional CSS. It's a long tedious job if you decide to do the encoding in logical structure and order, and then reposition things using CSS. This example is a good starting point for a discussion about how much work it's worth doing on such structures.
