### ISSUE TITLE
Temporal encoding for integration with LINCS

### ISSUE THREAD

**Issue by martindholmes** [MoEMLondon/MoEMLissues#3]
This ticket proposes three specific changes:

1. Schema changes:

The `<state>` element must be added to the content model of the `<place>` element, but must not be allowed anywhere else. This will mean changing the class membership of the `<state>` element and altering the content models of any macros which contain it to eliminate it from all other locations, then creating a custom content model for the `<place>` element which includes `<state>`. `<state>` will require all its dating attributes.

2. Encoding practice changes:

The following encoding practices will be adopted and tested within MoEML:
   i. Multiple `<location>` elements will be allowed inside `<place>`, and each will have a single `<geo>` element for a specific location for the place at a specific time[-range]. `@from-custom` and `@to-custom` attributes will be supplied whenever a location has a limited temporal range within the MoEML project's bounds. Where such attributes are not provided, there will be a global assumption that MoEML claims this location is valid for the period 1536 to 1666, but makes no claims outside that range. Where one or other bounding attribute is missing, the standard MoEML range boundary will be assumed.
   ii. Multiple `<state>` elements will be allowed withing `<place>`, with the same assumptions as to date ranges as apply to `<location>` elements. Each `<state>` element should also carry an `@ana` attribute pointing to a MoEML category, using the same private URI scheme as MoEML uses for `<catRef>/@target`. A corresponding `<catRef>` should also be present for the purposes of normal MoEML processing (we can check this with Schematron). Each `<state>` element represents the function a place had during a specific time range.
   iii. Multiple `<placeName>` elements are allowed in `<place>`, with the same dating attributes having the same purpose as discussed above. 
   
   All dating attributes will be in our normal MoEML mol:julian format.
   
3. GeoJSON output changes:
i. Each location element will be processed into a correct GeoJSON geometry as currently, ignoring the associated dating content, but then in a subsequent member of the GeoJSON "properties" object, an array of location date-ranges will be constructed, with each one assumed to correspond with the equivalent geometry.
ii. While the canonical place name for the place will be taken from the same place as currently in the TEI metadata, a new member of the GeoJSON "properties" object will hold an array of place names constructed from the `<placeName>` elements, each with a date-range as appropriate.
iii. Ditto for place function, as represented by `<state>` elements.

In the GeoJSON, all date ranges will be converted to proleptic Gregorian, before their month and day information will be stripped, providing a less granular date range, but one which is less likely to cause confusion for those not used to proleptic Gregorian.

The precise names and datatypes for the GeoJSON custom properties should be agreed ahead of time with the LINCS team, so that we use a standard vocabulary and their ingestion code can be more standardized.

**Comment by JanelleJenstad** [comment]
We will revisit this issue in late October 2022. MH would like to rethink the plan from first principles.

**Comment by martindholmes** [comment]
I believe this is now valid and working, but I'm still waiting to hear from EC at LINCS to say that it works for them.

**Comment by martindholmes** [comment]
It's working for LINCS, so I'm closing this.
